-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ProductOnSubCatalogue" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "SupplierOnOrder" ALTER COLUMN "totalHt" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalTtc" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "SupplierProductOnOrder" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;
