version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://remybeauperin:@localhost:5432/saas-v2
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: remybeauperin
      POSTGRES_PASSWORD:
      POSTGRES_DB: saas-v2
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
