-- CreateEnum
CREATE TYPE "Categories" AS ENUM ('VEGETABLES', 'FRUITS', 'MEAT', 'FISH', 'GROCERY', 'DAIRY', 'OTHER');

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "ref" DROP NOT NULL;
